package main

import (
	"testing"
)

func TestM(t *testing.T) {
	defer func() {
		err := recover()
		if err != nil {
			t.Errorf("following error occured while the main function was executed : ")
		}
	}()
	main()
}

func TestMain(m *testing.M) {
	m.Run()
}
